### ISSUE TITLE
Matching tags or releases on github and dockerhub

### ISSUE THREAD

**Issue by gotjoshua** [geosolutions-it/docker-geoserver#103]
I am just diving in to running geoserver, and I am trying to understand which version of which services and extensions are included in your public docker builds.

Could it be a good idea to create matching releases here on github, with changelogs that indicate the versions that are included?

**Comment by randomorder** [comment]
Hi @gotjoshua

On the docker hub you'll find images for all active GeoServer releases. At this point in time there are no plugins installed by default due [to a bug](https://github.com/geosolutions-it/docker-geoserver/issues/104) 

In [the README](https://github.com/geosolutions-it/docker-geoserver#readme) you can find instructions on how to add the set of plugins you need to the container both at image build time and at container run time

**Comment by gotjoshua** [comment]
> On the docker hub you'll find images for all active GeoServer releases.

yes, this i noticed, but then i was confused when i came to github and didn't find any tags nor releases that matched...

**Comment by randomorder** [comment]
Thanks for the input

The image tags on the docker hub tell you the GeoServer version included in the docker image. What's missing is the info on the version of the `docker-geoserver` repository used to build the image.

We could add this information to the final image in a text file and/or environment variable at image build time. Probably an extra [build argument](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)
