### ISSUE TITLE
Docker Hub autobuilds dependency issue

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#104]
`wget` is not available at images build time:
![image](https://user-images.githubusercontent.com/5264230/161526472-90a9d712-239d-45f9-bb73-0f0eb5e17b2d.png)

**Comment by PabloBaronetti** [comment]
@randomorder 

Can you please point me out where i can find the information to connect on the Docker Hub, so i can start working on this issue?

Thanks!

**Comment by PabloBaronetti** [comment]
@randomorder 

I maked a research on this but cannot find any information about the docker hub infrastructure, i think the best approach to handle this is on the Dockerfile definition (move the plugins related code into this file).

Thanks!

**Comment by PabloBaronetti** [comment]
Pull Request created: [Link](https://github.com/geosolutions-it/docker-geoserver/pull/105)
I tested the "latest" tag image and work correctly on my sandbox environment:
![image](https://user-images.githubusercontent.com/94936868/164559408-dc484a6a-a9fc-4f14-875d-6a7830a68887.png)

Thanks!

**Comment by randomorder** [comment]
thank you @PabloBaronetti
