### ISSUE TITLE
Is there a simple way to enable CORS with this image?

### ISSUE THREAD

**Issue by spydmobile** [geosolutions-it/docker-geoserver#107]
Hi I noticed there is a geoserver.conf, but dont know what it is for, I am trying to enable CORS for this image.

**Comment by randomorder** [comment]
Hi @spydmobile

`geoserver.conf` is the configuration file for nginx and in that ocnfiguration file CORS is enabled by default. Use you the `docker-compose.yml` file in the repository to [bring up the whole stack](https://github.com/geosolutions-it/docker-geoserver#using-geoserver-with-docker-compose)  (geoserver, postgresql, nginx) and CORS will be enabled

**Comment by spydmobile** [comment]
> `geoserver.conf` is the configuration file for nginx and in that ocnfiguration file CORS is enabled by default. Use you the `docker-compose.yml` file in the repository to [bring up the whole stack](https://github.com/geosolutions-it/docker-geoserver#using-geoserver-with-docker-compose) (geoserver, postgresql, nginx) and CORS will be enabled

Thank you! I am not using nginx or postgress, but I will see if can make things work knowing that geoserver.conf is for nginx (I use a broader NGINX proxy manager).
