### ISSUE TITLE
add source code version information to the docker images

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#108]
spawning from #103

would be nice to have a reference to the docker source files version in the final docker image for debugging purposes

**Comment by lpasquali** [comment]
Hello @zsarkad please read the related issue to understand the context and come back to me

**Comment by lpasquali** [comment]
Hello @zsarkad 
- Please add an argument to the Dockerfile like DOCKER_REPO_BRANCH
- check custom_build.sh script if is possible to add automatically a variable populated with branch name called DOCKER_REPO_BRANCH
Once changed Dockerfile and custom_build.sh please make a PR against geosolutions-it/docker-geoserver

**Comment by zsarkad** [comment]
changed Dockerfile, custom_build.sh and README accordingly
made PR request waiting for confirmation from @lpasquali

**Comment by zsarkad** [comment]
uploaded docker image

https://hub.docker.com/r/geosolutionsit/geoserver/tags

**Comment by randomorder** [comment]
Test latest 2.19 series and 2.20 series as well

**Comment by zsarkad** [comment]
tested  2.19 and 2.20 series , all work well

**Comment by zsarkad** [comment]
triggered and updated builds on the Docker hub

https://hub.docker.com/repository/registry-1.docker.io/geosolutionsit/geoserver/tags?page=1&ordering=last_updated
