### ISSUE TITLE
Cannot customize the admin password 

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/docker-geoserver#112]
Starting the container with something like:

`docker run -it  -p 8083:8080 -e ADMIN_PASSWORD='Geos' geosolutionsit/geoserver`

fails to customize the password, in the logs I can see:

`/usr/bin/env: ‘bash\r’: No such file or directory`

**Comment by randomorder** [comment]
thanks for reporting @aaime
I'll have a look

**Comment by posarelli** [comment]
Deployed locally seems not having this problem... @randomorder

**Comment by randomorder** [comment]
It's a branch specific issue. Likely due to my commits here: https://github.com/geosolutions-it/docker-geoserver/compare/master...fedgeo2022

Try to reproduce with this command instead @posarelli 
` docker run -it -p 8083:8080 -e ADMIN_PASSWORD='Geos' geosolutionsit/geoserver:fedgeo2022`

**Comment by posarelli** [comment]
@randomorder : confirmed problem on this branch.
