### ISSUE TITLE
Feature Request:  Support EXTRA_GEOSERVER_OPTS

### ISSUE THREAD

**Issue by hbruch** [geosolutions-it/docker-geoserver#133]
In case someone wants to start the docker container with additional `GEOSERVER_OPTS`, all the default opts need to be redefined.

A new ENV variable `EXTRA_GEOSERVER_OPTS` which gets appended to `GEOSERVER_OPTS` would avoid this.

Note: [Dockerfile#L98](https://github.com/geosolutions-it/docker-geoserver/blob/master/Dockerfile#L98) defines `JAVA_OPTS`, though [catalina.sh](https://github.com/apache/tomcat/blob/9.0.83/bin/catalina.sh#L47-L52) suggests to rather use `CATALINA_OPTS` instead of `JAVA_OPTS`

**Comment by randomorder** [comment]
thanks @hbruch 
I would split this in two:
- changing JAVA_OPTS to CATALINA_OPTS to align with what Apache Tomcat recommends
- adding the extra variable "EXTRA_GEOSERVER_OPTS" empty by default to the dockerfile and is appended to the CATALINA_OPTS by the [entrypoint script](https://github.com/geosolutions-it/docker-geoserver/blob/master/entrypoint.sh) right before tomcat is started with [catalina.sh](https://github.com/geosolutions-it/docker-geoserver/blob/master/entrypoint.sh#L4)

**Comment by hbruch** [comment]
Yes, great, thank you!

And `GEOSERVER_OPTS` should be added to CATALINA_OPTS in the `entrypoint.sh` also, not in the Dockerfile, as currently a `GEOSERVER_OPTS` passed as ENV VAR is not evaluated, as JAVA_OPTS is extrapolated at build time already.

**Comment by randomorder** [comment]
merged. Sorry it took some time @hbruch 
thanks @camuffo
