### ISSUE TITLE
Add LICENSE to improve clarity on intention behind this repository

### ISSUE THREAD

**Issue by LukeParky** [geosolutions-it/docker-geoserver#152]
Hi, I think it would benefit this project to be clear about software licensing.
I see that geosolutions-it likes to work in open-source, however, it's not entirely clear if this project was intended to be open-source or not.

I would like to explore using this project to solve some of the issues I've had with other geoserver images.

Could someone please comment on if this project is All Rights Reserved, or if there is some discussion already around the licensing?

**Comment by randomorder** [comment]
Thanks for pointing it out @LukeParky  . I'm adding the license file to the repository.
