### ISSUE TITLE
Dockerfile is ignoring the catalina-wrapper script

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#28]
Latest version of the image is not adding  the script and not overwriting the CMD to use it

**Comment by jemacchi** [comment]
@randomorder 
I have added feature related to catalina-wrapper.sh in branch for C196, but probably you will want later to add it to master.
Check [PR](https://github.com/geosolutions-it/docker-geoserver/pull/29) when possible.

**Comment by randomorder** [comment]
merged into `geosolutions-it:C196`
tanks
