### ISSUE TITLE
Ansible role for Tomcat and GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#30]
hey @lpasquali 
I can see an imnplmementation on this [branch](https://github.com/geosolutions-it/DevOps/tree/ansible_implementations/ansible-production-geoserver) what's the status of it? is it usable / can you make a MR?

**Comment by lpasquali** [comment]
yes, it needs some enhancement but it is basically usable  

- better defaults for JAVA_OPS
- latest jndi optimizations
- audit logs plugin, enabling, location
