### ISSUE TITLE
Multi platform compatible docker image builds.

### ISSUE THREAD

**Issue by agpenton** [geosolutions-it/docker-geoserver#38]
I noticed that the build of the docker image in the repository is just `linux/amd64`, and in my case that image is not useful, cause my system is on ARM architecture. So I got 2 errors:
1. since the image is on amd64, I can't run that image.
2. I've tried to build the image from the Dockerfile, and I got an error when apt try to install `libjpeg-turbo-official`.
    * This is part of the output of the error: 
       ```#15 4.156
            #15 4.361 dpkg: error processing archive ./libjpeg-turbo-official_1.5.3_amd64.deb (--install):
            #15 4.361  package architecture (amd64) does not match system (arm64)
            #15 4.651 Errors were encountered while processing: 
            #15 4.652  ./libjpeg-turbo-official_1.5.3_amd64.deb
            ------
            error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c wget 
            https://downloads.sourceforge.net/project/libjpeg-turbo/1.5.3/libjpeg-turbo-official_1.5.3_amd64.deb && dpkg -i ./libjpeg*.deb && apt-get -f install]: exit code: 1
```

**Comment by randomorder** [comment]
what's the status of this one @agpenton ?
I see two closed PRs in the repo

**Comment by randomorder** [comment]
@agpenton ?
