### ISSUE TITLE
geoserver datadir is not populated on custom_build.

### ISSUE THREAD

**Issue by agpenton** [geosolutions-it/docker-geoserver#44]
Geoserver datadir is not populated with real data, or at least some of them are missing when you build the GeoServer image with the `custom_build.sh` script.

**Comment by randomorder** [comment]
can you please take a look @lpasquali 
looks like the datadir parameter is ignored. Specifically, how do we set `GEOSERVER_DATA_DIR_DIRECTORY`?
https://github.com/geosolutions-it/docker-geoserver/blob/master/custom_build.sh#L153

**Comment by lpasquali** [comment]
> can you please take a look @lpasquali
> looks like the datadir parameter is ignored. Specifically, how do we set `GEOSERVER_DATA_DIR_DIRECTORY`?
> https://github.com/geosolutions-it/docker-geoserver/blob/master/custom_build.sh#L153

I fixed that, there was a name difference between the real variable pointing to resources/geoserver-datadir and such variable, updated the help and Readme as well. fixed a bug which deleted a custom datadir by default...
