### ISSUE TITLE
An estrange folder appear in the docker image when build with custom_build.

### ISSUE THREAD

**Issue by agpenton** [geosolutions-it/docker-geoserver#45]
apparently, when you build with custom_build script the source folder **`https:`** of the file downloaded appear in the source folder and inside the docker image.

**Comment by randomorder** [comment]
please be more descriptive @agpenton  and add the steps to replicate the issue and some logs

**Comment by agpenton** [comment]
@randomorder after an investigation of the issue, i found out that the directory is created by this command:
```bash
if [ ! -e "${PLUGIN_ARTIFACT_URL}" ]; then
      mkdir -p "${PLUGIN_ARTIFACT_URL}"
  fi
``` 
The PR for this issue is [here](https://github.com/geosolutions-it/docker-geoserver/pull/53)
