### ISSUE TITLE
Run tomcat as non-root user

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#50]
Current  implementation of the docker image is running tomcat as root user
![image](https://user-images.githubusercontent.com/5264230/110489760-edcb6100-80ef-11eb-8e53-82869b6a1c61.png)

It'd be nice to be able to run the service as a non-root user from a security standpoint. This is a popular request among our customers

**Comment by lpasquali** [comment]
@randomorder https://github.com/geosolutions-it/docker-geoserver/pull/61
