### ISSUE TITLE
custom_build.sh does not support RC or dev versions 

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/docker-geoserver#52]

**Comment by lpasquali** [comment]
@randomorder I feared something changed specially in the geoserver war plugin URL structure but actually I tried several different build and it works without modifications with 2.19-RC

**Comment by randomorder** [comment]
what about "dev versions"?

**Comment by lpasquali** [comment]
> what about "dev versions"?

@randomorder  "2.19-RC" is the only one under tab development on the geoserver downloads page
do you mean nightly builds of what is called main now (formerly master)?
I just noticed that nightly builds of "[main](https://build.geoserver.org/geoserver/main)" are pointing to "[master](https://build.geoserver.org/geoserver/master)" which as being changed gives 404 (broken link evidenced in image below)

![Screenshot from 2021-03-16 10-07-08](https://user-images.githubusercontent.com/1780406/111283744-bb65ba80-863f-11eb-9cbe-31f94f66e6ad.png)

**Comment by randomorder** [comment]
so that needs fixing..

For nighly builds, there is one for each active branch https://build.geoserver.org/view/geoserver/

**Comment by lpasquali** [comment]
> so that needs fixing..
> 
> For nighly builds, there is one for each active branch https://build.geoserver.org/view/geoserver/

Ok nightly builds should have no issues, besided master to main switch that has its dedicated issue @randomorder

**Comment by lpasquali** [comment]
@randomorder where should I report the broken URL?

**Comment by randomorder** [comment]
I don't understand what is broken
Anyway GeoServer skype group if you need some interactive input and JIRA otherwise

**Comment by lpasquali** [comment]
> I don't understand what is broken
> Anyway GeoServer skype group if you need some interactive input and JIRA otherwise

the link referred in the image above points to https://build.geoserver.org/geoserver/master instead of https://build.geoserver.org/geoserver/main

**Comment by randomorder** [comment]
Please make a PR here https://github.com/geoserver/geoserver.github.io/blob/main/download/index.html#L208

Take the chance to grep the repo for "master" 
You'll never know :)

**Comment by lpasquali** [comment]
@randomorder it has been done in a branch named after 2.19-RC here https://github.com/geoserver/geoserver.github.io/commit/fb5fb308ea2a2ff829edbafe3d3d52cd5b9b93c1
maybe it is not needed anymore

**Comment by randomorder** [comment]
let's see if this gets fixed for 2.19.0

**Comment by lpasquali** [comment]
@randomorder I checked after 2.19.0 release and page is fixed, we can close this

**Comment by randomorder** [comment]
thanks
