### ISSUE TITLE
custom_build.sh does not install correctly official plugins for nightly releases anymore

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/docker-geoserver#57]
step to reproduce:

- add some plugins both ext and community:
```
    download_plugin ext jp2k
    download_plugin ext control-flow
    download_plugin ext libjpeg-turbo
    download_plugin community opensearch-eo
```
- run custom_build.sh like this:
```
./custom_build.sh my-docker-tag 2.18.x 2.18.x nodatadir no_pull
```

as a result only community plugin will be installed.

**Comment by lpasquali** [comment]
problem is in lines [here](https://github.com/geosolutions-it/docker-geoserver/blob/master/custom_build.sh#L60-L87) looking at the case there seem to be 4 categories of choice but there should be only 3 where:

- Version has an x as minor.
- Version is equal to "main".
- Version is anything else.

**Comment by randomorder** [comment]
please fix it once and for all and port the change to the PR for the official docker image for geoserver @lpasquali

**Comment by lpasquali** [comment]
made PR: https://github.com/geosolutions-it/docker-geoserver/pull/58

@randomorder let me know so when merged I will align with the official

**Comment by randomorder** [comment]
merged
please close the issue when done

**Comment by lpasquali** [comment]
what's missing: port to official docker image

**Comment by lpasquali** [comment]
@randomorder synced with offiial PR

**Comment by randomorder** [comment]
thanks
