### ISSUE TITLE
Container doesn't stop on SIGINT

### ISSUE THREAD

**Issue by sycured** [geosolutions-it/docker-geoserver#68]
The container needs to stop on SIGINT (CTRL+C)

### How to reproduce

1. Start the container using `docker run --rm -p 8080:8080 geosolutionsit/geoserver:2.19.1`
2. Waiting to see:
```
INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [30964] milliseconds
catalina.sh run
```
3.  Doing SIGINT doing CTRL+C, you'll see something like: `^C^C^C^C^C^C^C^C^C^C` (one for each time you send it)

### Expected behavior

The container stop on receiving SIGINT

### Actual behavior

SIGINT isn't handled and the container needs to be stopped using `docker stop` via another terminal

### Workaround

Starting the container using `--init` flag: `docker run --rm --init -p 8080:8080 geosolutionsit/geoserver:2.19.1`

### Possible fix

- updating the documentation about `--init` flag
- using an init directly inside the container like [s6-overlay](https://github.com/just-containers/s6-overlay)
 
### Additional information

- [My Container Won't Stop on Ctrl-C, and Other Minor Tragedies](https://www.weave.works/blog/my-container-wont-stop-on-ctrl-c-and-other-minor-tragedies/)
- [Specify an init process](https://docs.docker.com/engine/reference/run/#specify-an-init-process)
- [Run multiple services in a container](https://docs.docker.com/config/containers/multi-service_container/)
- [Choosing an init process for multi-process containers](https://ahmet.im/blog/minimal-init-process-for-containers/)

**Comment by randomorder** [comment]
that's interesting I don't see a strong enough point to add this external dependency to the image

Thank you anyway
