### ISSUE TITLE
Update docker images for GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#69]
tag _latest_ is running GeoServer 2.18.2

**Comment by drumbsd** [comment]
Manually pushed geoserver:latest built on 2.19.2

https://hub.docker.com/layers/geosolutionsit/geoserver/latest/images/sha256-9bd8256f3208aa96c876f04479c1330e21d48db9d0c57447f49ab306601267cd?context=explore

**Comment by randomorder** [comment]
thanks. Let's wait for Luca to come back and clarify how latest is built and pushed

**Comment by drumbsd** [comment]
Doing one additional test.

**Comment by randomorder** [comment]
please check this with @lpasquali, @drumbsd

**Comment by lpasquali** [comment]
Hello @randomorder
I think docker "latest" tag is not handled by the docker hub hooks we use to push in the repo.
I would add NEWEST_VERSION (as LATEST has different meaning, it is the "unreal" version for custombuild) in docker hub.
Then logic for tagging could be easily implemented in https://github.com/geosolutions-it/docker-geoserver/blob/master/hooks/push script
like

```
# check if {DOCKER_REPO}:$NEWEST_VERSION exists 
docker pull ${DOCKER_REPO}:$NEWEST_VERSION
docker tag "${DOCKER_REPO}:$NEWEST_VERSION" ${DOCKER_REPO}:latest
```

**Comment by randomorder** [comment]
Please take care of it @drumbsd 
Luca to review

**Comment by drumbsd** [comment]
@randomorder I see that the content of test_hooks.sh is different from the ENV inside dockerhub. They need to be aligned or not?

**Comment by randomorder** [comment]
please check with @lpasquali

**Comment by lpasquali** [comment]
> @randomorder I see that the content of test_hooks.sh is different from the ENV inside dockerhub. They need to be aligned or not?

@drumbsd I usually align them going on http://geoserver.org/download/ then click archived 

![Screenshot from 2021-08-18 16-30-30](https://user-images.githubusercontent.com/1780406/129917003-e2e5e7cf-7574-46ea-a4a9-2dc532f9404f.png)
and dev versions

![Screenshot from 2021-08-18 16-32-46](https://user-images.githubusercontent.com/1780406/129917368-cf200118-9fa7-40c0-acdf-a94febdcdfab.png)

then I align variables on hub and test_hooks.sh accordingly

**Comment by drumbsd** [comment]
I'm going to test the new branch build on dockerhub @lpasquali

**Comment by drumbsd** [comment]
@lpasquali branch has been tested. Images were pushed. I pulled 

```
geosolutionsit/geoserver:latest
```
run it and is correctly built on 2.19.2

**Comment by drumbsd** [comment]
![image](https://user-images.githubusercontent.com/6428880/130054037-138831d5-0783-4b5a-8b10-b2691262cdd3.png)
