### ISSUE TITLE
Geoserver login forms not sending to https

### ISSUE THREAD

**Issue by JohnnyMoonlight** [geosolutions-it/docker-geoserver#78]
I have set up a geoserver within a K8S environment. As base, I use the official [docker image](https://hub.docker.com/r/geosolutionsit/geoserver/). The server is reachable internally via https and will, when fully configured, be publicly accessible.

When I try to login to geoserver (lets say under the url 'https://geoserver.institute.com'), I see the default entry page, but i cannot login, because the login form points to 'http://geoserver.institute.com/geoserver/j_spring_security_check' (http, not https).

However, I can change the html content to send the request to https. Doing so enables me to successfully log in. Since this is quite a dirty hack, I would appreciate a solution.

Thank you in advance!

**Comment by randomorder** [comment]
Hi @JohnnyMoonlight 

By your description it looks like you stumbled into a bug in geoserver. There is [an associated ticket](https://osgeo-org.atlassian.net/browse/GEOS-10158) in geoserver's ticketing system and has been resolved in in the development branch.

The fix will be included in he upcoming GeoServer 2.20 stable release which will happen in about a week. You can try upgrading once 2.20 is out.

**Comment by JohnnyMoonlight** [comment]
Alright, thanks for the heads up!
