### ISSUE TITLE
docker-compose up not working 

### ISSUE THREAD

**Issue by dawitanelay** [geosolutions-it/docker-geoserver#85]
Docker-compose version used
 `docker-compose version 1.29.2, build 5becea4c`
Command used in the write directory
`docker-compose up `
ERROR: 
`The Compose file './docker-compose.yml' is invalid because:
services.geoserver.depends_on contains an invalid type, it should be an array`

**Comment by randomorder** [comment]
Hi @dawitanelay 
did you make any changes to your local docker-compose file? Can you please attach it to the issue?

**Comment by dawitanelay** [comment]
@randomorder I didn't make any changes.

**Comment by drumbsd** [comment]
https://stackoverflow.com/questions/47710767/what-is-the-alternative-to-condition-form-of-depends-on-in-docker-compose-versio

Seems that condition + depends_on is no longer supported on docker-compose.yml version 3.

**Comment by drumbsd** [comment]
Ok got the problem. We need at least 1.29.0 docker-compose to be able to start this docker-compose.yml

**Comment by dawitanelay** [comment]
after restarting docker daemon works. thank you @drumbsd
