### ISSUE TITLE
Improve documentation for docker-compose usage

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/docker-geoserver#93]
We want to improve the documentation for the docker-compose usage with
- a step by step documentation on how to start the stack with docker-compose
- how to connect to postgresql
- externalize the data directory
- how to use an alternative war file

**Comment by PabloBaronetti** [comment]
Sandbox testing (docker-compose GeoServer stack deploy) and polish documentation for review.

**Comment by PabloBaronetti** [comment]
Repository: [docker-geoserver](https://github.com/geosolutions-it/docker-geoserver)

[Pull Request](https://github.com/geosolutions-it/docker-geoserver/pull/94) created:

Docker-Compose Documentation Improvement

Creation of a Sandbox Environment to accurate testing the steps and tasks detailed in the documentation (and for future requirements as well).
* Deployment from scratch of the docker-compose GeoServer stack
* Complete testing of all the steps and tasks 

Documentation of this procedure, on the readme file of the docker-geoserver repository.

**Comment by PabloBaronetti** [comment]
Improvement to the volumes and environment variables section

**Comment by randomorder** [comment]
thanks @PabloBaronetti
