### ISSUE TITLE
There is a typo in a rm command

### ISSUE THREAD

**Issue by razor54** [geosolutions-it/docker-geoserver#97]
https://github.com/geosolutions-it/docker-geoserver/blob/92d91dcec0b981d478936ce373254547f9e2834c/custom_build.sh#L41

Nothing that important, but just to reference.

**Comment by razor54** [comment]
Found out 2 more, even less relevant but..

https://github.com/geosolutions-it/docker-geoserver/blob/92d91dcec0b981d478936ce373254547f9e2834c/custom_build.sh#L54

https://github.com/geosolutions-it/docker-geoserver/blob/master/custom_build.sh#L56

**Comment by randomorder** [comment]
thank you @razor54 
If you could create a pull request to fix all the typos it would be great

**Comment by razor54** [comment]
https://github.com/geosolutions-it/docker-geoserver/pull/98
Maybe there are more typos, I didn't look at other files yet.
cheers

**Comment by razor54** [comment]
PR was merged so this issue is no longed needed
